- name: Install packages 
  hosts: frontend 
  become: yes
  tasks: 
  - name: Install packages in loop 
    ansible.builtin.package: 
     name: "{{ item }}"
     state: installed 
    loop:
    - mysql 
    - nginx 
    - zip