- name: functions 
  hosts: local 
  connection: local 
  vars: 
   persons: "Ramesh,Suresh,Raheem,Joesph"
  tasks: 
  - name: check undefined variable
    ansible.builtin.debug: 
     msg: "Hello, {{ person | default('Ramesh') }}"

  - name: To split the names 
    ansible.builtin.debug: 
     msg: "Hello, {{ persons | split(',') }}"