- name: functions 
  hosts: local 
  connection: local 
  vars: 
   persons: "Ramesh,Suresh,Raheem,Joesph"
  tasks: 
  - name: check undefined variable
    ansible.builtin.debug: 
     msg: "Hello, {{ person | default('Ramesh') }}"

  - name: To split the names 
    ansible.builtin.debug: 
     msg: "Hello, {{ persons | split(',') }}"

  - name: convert map into list 
    vars: 
     course:
      name: ansible
      duration: 10HR
      trainer: sivakumar
    ansible.builtin.debug: 
     msg: "Course Info: {{ course | dic2items }}"

  - name: convert list to map 
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10HR'}
      - {'key': 'trainer', 'value': 'sivakumar'}
    ansible.builtin.debug: 
     msg: "Course Info: {{ course | items2dict }}"
    
