- name: install nginx 
  hosts: dynamic-frontend
  become: yes 
  tasks: 
  - name: install nginx 
    ansible.builtin.dnf: 
     name: nginx 
     state: installed 

  - name: run the nginx service 
    ansible.builtin.service: 
     name: nginx 
     state: started 
     enabled: yes 
