- name: create ec2 and r-53 records 
  hosts: local
  connection: local 
  vars: 
    instances: 
    - mysql 
    - frontend 
    - backend 
    subnet_id: subnet-02f5946970c07b2be
    sg_id: sg-00074df5f97ffa960
    zone: sivadevops.fun 
  tasks: 
  - name: craete ec2 instances 
    amazon.aws.ec2_instance:
     name: "{{ item }}"
     vpc-subnet_id: "{{ subnet_id }}"
     instance_type: t3.micro 
     security_group: "{{ sg_id }}"
     image_id: ami-09c813fb71547fc4f
     tags: 
      Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output 
   
  - name: print ec2_output 
    ansible.builtin.debug: 
     msg: "{{ ec2_output }}"
    
